// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLZTdMoMhA1HCGMRwigm5jnVU4BsS-6GQ',
    appId: '1:643714794185:web:cf0a36366495f36b038318',
    messagingSenderId: '643714794185',
    projectId: 'driving-div',
    authDomain: 'driving-div.firebaseapp.com',
    storageBucket: 'driving-div.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHqWZBCYbKM9aza2x17DfXbTtm0djEuMk',
    appId: '1:643714794185:android:929cdc6393293146038318',
    messagingSenderId: '643714794185',
    projectId: 'driving-div',
    storageBucket: 'driving-div.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzU-mJdcWv5EWI6xYLnwnPxXNRlGSxkdA',
    appId: '1:643714794185:ios:8c7d8134a9dc2c76038318',
    messagingSenderId: '643714794185',
    projectId: 'driving-div',
    storageBucket: 'driving-div.appspot.com',
    iosClientId: '643714794185-sl4p3cvml5so27g7k9ojjbonedipntnh.apps.googleusercontent.com',
    iosBundleId: 'com.example.drivingDiv',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzU-mJdcWv5EWI6xYLnwnPxXNRlGSxkdA',
    appId: '1:643714794185:ios:8c7d8134a9dc2c76038318',
    messagingSenderId: '643714794185',
    projectId: 'driving-div',
    storageBucket: 'driving-div.appspot.com',
    iosClientId: '643714794185-sl4p3cvml5so27g7k9ojjbonedipntnh.apps.googleusercontent.com',
    iosBundleId: 'com.example.drivingDiv',
  );
}
